---
title: a Velvet Uproar
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: "/images/about.jpg"
      map:
        latitude:
        longitude: 
email: avelvetuproar@gmail.com
about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus viverra
  ante in ipsum hendrerit, ut tristique neque aliquet. Donec magna lacus, laoreet
  et leo ut, blandit pellentesque nisi. Etiam congue libero non augue tempor, quis
  dapibus mauris interdum.
baseurl: ''
url: http://avelvetuproar.com
github_username: tomsmit
markdown: kramdown
